[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name         = "LocalTuya integration"
version      = "5.2.4"
license      = "GPL-3.0"
license-files = ["LICENSE*"]
description  = "local handling for Tuya devices"
readme       = "README.md"
authors      = [
    {name = "rospogrigio", email = ""}
]
requires-python = ">=3.13.0"

[project.urls]
"Homepage" = "https://github.com/rospogrigio/localtuya"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["custom_components*"]
